// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.2
// source: src/api/v1/inventory/inventory.proto

package inventory

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InventorySvc_Read_FullMethodName = "/inventory.InventorySvc/Read"
)

// InventorySvcClient is the client API for InventorySvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InventorySvcClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
}

type inventorySvcClient struct {
	cc grpc.ClientConnInterface
}

func NewInventorySvcClient(cc grpc.ClientConnInterface) InventorySvcClient {
	return &inventorySvcClient{cc}
}

func (c *inventorySvcClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, InventorySvc_Read_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InventorySvcServer is the server API for InventorySvc service.
// All implementations must embed UnimplementedInventorySvcServer
// for forward compatibility
type InventorySvcServer interface {
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	mustEmbedUnimplementedInventorySvcServer()
}

// UnimplementedInventorySvcServer must be embedded to have forward compatible implementations.
type UnimplementedInventorySvcServer struct {
}

func (UnimplementedInventorySvcServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedInventorySvcServer) mustEmbedUnimplementedInventorySvcServer() {}

// UnsafeInventorySvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InventorySvcServer will
// result in compilation errors.
type UnsafeInventorySvcServer interface {
	mustEmbedUnimplementedInventorySvcServer()
}

func RegisterInventorySvcServer(s grpc.ServiceRegistrar, srv InventorySvcServer) {
	s.RegisterService(&InventorySvc_ServiceDesc, srv)
}

func _InventorySvc_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InventorySvcServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InventorySvc_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InventorySvcServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InventorySvc_ServiceDesc is the grpc.ServiceDesc for InventorySvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InventorySvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inventory.InventorySvc",
	HandlerType: (*InventorySvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _InventorySvc_Read_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/api/v1/inventory/inventory.proto",
}
