// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           pgtype.UUID
	Email        string
	PasswordHash string
	IsActive     pgtype.Bool
	IsVerified   pgtype.Bool
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type AccountsSession struct {
	ID           pgtype.UUID
	AccountID    pgtype.UUID
	RefreshToken string
	UserAgent    pgtype.Text
	IpAddress    pgtype.Text
	IssuedAt     pgtype.Timestamp
	ExpiresAt    pgtype.Timestamp
	CreatedAt    pgtype.Timestamp
}
